# Generated by Django 2.2.4 on 2019-11-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='pictures', height_field=400, upload_to='', width_field=800),
        ),
    ]
