# Generated by Django 2.2.4 on 2019-11-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyshop', '0003_auto_20191115_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
