# Generated by Django 2.2.4 on 2019-11-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyshop', '0004_auto_20191115_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_img',
        ),
    ]
