# Generated by Django 2.2.4 on 2019-11-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyshop', '0009_auto_20191115_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='', height_field=models.IntegerField(verbose_name=800), upload_to='media', width_field=models.IntegerField(verbose_name=400)),
        ),
    ]
