# Generated by Django 2.2.4 on 2019-11-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyshop', '0010_auto_20191117_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.IntegerField()),
                ('card_type', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
